### ISSUE TITLE
Complete MVP1 deployment to IBM Cloud

### ISSUE THREAD

**Issue by demilolu** [embrace-call-for-code/taketwo-datascience#39]
### Background on the problem the feature will solve/improved user experience
Upkar has deployed the MVP1 to Watson Machine Learning. The code is currently in this [branch](https://github.com/Call-for-Code-for-Racial-Justice/TakeTwo-DataScience/tree/ul-updates)
and needs to be moved to the main branch. 

### Tasks 

- [ ] Determine how to update/converge with various branches
- [ ] Discuss how to update notebooks: since Upkar's notebook includes deployment.  @Preetikasri 
- [ ] Update documentation with link to deployed model on Watson Machine Learning (TakeTwo and TakeTwo-DataScience) - @upkarlidder 
- [ ] possibly integrate to TakeTwo Lab: https://github.com/Call-for-Code-for-Racial-Justice/TakeTwo/issues/31 - @upkarlidder 
- [ ] demo to Morgan Stanley team

Description of the development tasks needed to complete this issue, including tests, 

### Acceptance Criteria 
Standards we believe this issue must reach to be considered complete and ready for a pull request. E.g precisely all  the user should be able to do with this update, performance requirements, security requirements, etc as appropriate.

**Comment by upkarlidder** [comment]
Watson Machine Learning (WML) documentation - https://dataplatform.cloud.ibm.com/docs/content/wsj/analyze-data/ml-samples-overview.html?context=analytics

WML API - https://cloud.ibm.com/apidocs/machine-learning?code=python#authentication
